app.py
from flask import Flask, render_template
from routes.login import loginbp
from routes.validation import validationbp
from databases import database
import flask_login
import os


#   -->App Config<--
app = Flask(__name__)
app.secret_key = os.getenv('private_key')

#   -->Login Manager<--
login_manager = flask_login.LoginManager()
login_manager.init_app(app)

@login_manager.user_loader
def user_loader(email):
    if not database.email_exists(email):
        return
    
    user = database.get_user(email)
    return user


@app.route('/')
def index():

    print(flask_login.current_user)
    if flask_login.current_user.is_authenticated:
        print('Rola')
        return render_template('profile_details.html')

    return render_template('index.html')

app.register_blueprint(loginbp, url_prefix = '/login')
app.register_blueprint(validationbp, url_prefix= '/validate')

if __name__ == '__main__':
    app.run('0.0.0.0', debug=True)

routes/login.py
from flask import Blueprint, request, render_template
import flask_login

loginbp = Blueprint('login', __name__)

@loginbp.route('/', methods=['GET', 'POST'])
def login():
    
    if request.method == 'GET':
        return render_template('signup.html')

    elif request.method == 'POST':
        return render_template('signup.html')

routes/validation.py
from flask import Blueprint, request, render_template
import jwt
from databases import database
from pydantic import BaseModel
from flask_login import login_user, current_user

validationbp = Blueprint('validation', __name__)

#   -->Response Model<--
class Response(BaseModel):
    status: str = ''
    isValid: bool = False

#   -->Validations<--
def check_email(user_email: str):

    if user_email.find('@') < 0: #checks if the email has a handle
        status = 'Invalid email address'
        return Response(status=status).model_dump()
    
    elif len(user_email) > 50: #checks if the email is too long
        status = 'Email address too long'
        return Response(status=status).model_dump()

    elif not user_email.replace('.', '').split('@')[0].isalnum(): #checks if the email contains illegal characters (excludes the '.')
        status = 'Invalid email address'
        return Response(status=status).model_dump()
    
    elif database.email_exists(user_email):
        status = 'Email already in use'
        return Response(status=status).model_dump()

    return Response(isValid=True).model_dump()

def check_password(user_password: str):

    if len(user_password) < 6: #checks if the password is too short
        status = 'Password must be atleast 6 characters long'
        return Response(status=status).model_dump()
    
    return Response(isValid=True).model_dump()

def check_username(username: str):

    if len(username) < 4 or len(username) > 20:
        status = 'Username Must at least 4 characters long and less than 20 characters long'
        return Response(status=status).model_dump()
    
    if not username.isalnum():
        status = 'Username must include only letters and numbers'
        return Response(status=status).model_dump()
    
    if database.username_exists(username):
        status = 'Username already taken'
        return Response(status=status).model_dump()

    return Response(isValid=True).model_dump()

def check_quote(userquote: str):

    if len(userquote) < 3 or len(userquote) > 150:
        status = 'Your Quote must have between 3 and 150 characters'
        return Response(status=status).model_dump()
    
    if database.quote_exists(userquote):
        status = 'Someone has already registered this Quote'
        return Response(status=status).model_dump()
    
    return Response(isValid=True).model_dump()

#   -->Routes<--
@validationbp.route('/email', methods=['POST'])
def validate_email():

    user_email=request.form['useremail'].strip()
    email_check = check_email(user_email)
    
    return render_template('form_email.html', status=email_check['status'], useremail=user_email)

@validationbp.route('/password', methods=['POST'])
def validate_password():

    user_password=request.form['userpassword'].strip()
    password_check = check_password(user_password)
    
    return render_template('form_password.html', status=password_check['status'], userpassword=user_password)
    
@validationbp.route('/username', methods=['POST'])
def validate_username():

    username=request.form['username'].strip()
    username_check=check_username(username)
    return render_template('form_username.html', status=username_check['status'], username=username)

@validationbp.route('userquote', methods=['POST'])
def validate_quote():
    userquote=request.form['userquote'].strip()
    userquote_check = check_quote(userquote)
    return render_template('form_quote.html', status=userquote_check['status'], userquote=userquote)

@validationbp.route('/submit', methods=['POST'])
def validate_submit():

    user_email=request.form['useremail'].strip()
    user_password=request.form['userpassword'].strip()
    username=request.form['username'].strip()
    userquote=request.form['userquote'].strip()

    if check_email(user_email)['isValid'] and check_password(user_password)['isValid'] and check_username(username)['isValid'] and check_quote(userquote)['isValid']:

        user_password = jwt.encode({'password': f'{user_password}'}, database.private_key, algorithm='HS256')
        database.create_user(user_email, user_password, username, userquote)

        login_user(database.get_user(user_email))

        return render_template('profile_details.html', useremail=current_user.email)

    

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block title %}
    <title>Document</title>
    {% endblock title %}

    <!--Imports-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://unpkg.com/htmx.org@1.9.10" integrity="sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="{{url_for('static', filename='css/site.css')}}" rel="stylesheet">
    <!--/Imports-->
</head>
<body>

    <header id="the-header">
        {% block header %}
            
            <!--Navigation-->
            {% block navbar %}
                <nav class="navbar navbar-expand-sm border-bottom border-2 border-black">
                    <div class="container d-flex justify-content-center">
                        <a class="navbar-brand fs-2 text-black" href="#the-header">SinQuo</a>
                    </div>
                </nav>            
            {% endblock navbar %}

        {% endblock header %}
    </header>

    <main>
        {% block main %}
        {% endblock main %}
    </main>

    <footer>
        {% block footer %} 
        {% endblock footer %}
    </footer>

    <!--Imports-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/form_email.html
<div class="mb-3" hx-target="this" hx-swap="outerHTML">
    <input type="email" hx-post="{{url_for('validation.validate_email')}}" name="useremail" class="form-control" value="{{useremail}}" placeholder="Email">
    <p class="text-danger">{{status}}</p>
</div>

templates/form_password.html
<div class="mb-3" hx-target="this" hx-swap="outerHTML">
    <input type="password" hx-post="{{url_for('validation.validate_password')}}" name="userpassword" class="form-control" value="{{userpassword}}" placeholder="Password">
    <p class="text-danger">{{status}}</p>
</div>

templates/form_quote.html
<div class="mb-3" hx-target="this" hx-swap="outerHTML">
    <input type="text" hx-post="{{url_for('validation.validate_quote')}}" name="userquote" class="form-control" placeholder="Username" value="{{userquote}}">
    <p class="text-danger">{{status}}</p>
</div>

templates/form_username.html
<div class="mb-3" hx-target="this" hx-swap="outerHTML">
    <input type="text" hx-post="{{url_for('validation.validate_username')}}" name="username" class="form-control" placeholder="Username" value="{{username}}">
    <p class="text-danger">{{status}}</p>
</div>

templates/index.html
{% extends 'base.html' %}

{% block main %}
    
<div id="content" class="col d-flex flex-column justify-content-between" style="height: 55vh; margin-top: 10vh;">
    
    <!--The Reason-->
    <div id="reason" class="container-fluid">

        <div class="container-fluid d-flex flex-column align-items-center border border-2 border-black rounded-2 py-2 w-50">

            <p class="fs-1">Ever wanted to have you own Quoute?</p>
            <p class="fs-4 mt-3">Don't waste more time and claim your quote</p>

        </div>

    </div>

    <!--The call to action-->
    <div id="call" class="container d-flex justify-content-center">

        <button hx-get="{{url_for('login.login')}}" hx-target="#content" type="button" id="call-btn" class="fs-3">Unleash Your Wisdom!</button>
    
    </div>
</div>


{% endblock main %}

templates/login.html
<div class="container-fluid mb-3">
    <div id="interaction" hx-swap="outerHTML" class="container-fluid border border-2 border-black rounded-2 py-3 w-50 mb-3">

        <form class="form">

            <div class="fs-1 mb-3">Login </div>

            <div class="mb-3" hx-target="this" hx-swap="outerHTML">
                <input type="email" hx-post="{{url_for('validation.validate_email')}}" name="useremail" class="form-control" placeholder="Email">
            </div>
            <div class="mb-3" hx-target="this" hx-swap="outerHTML">
                <input type="password" hx-post="{{url_for('validation.validate_password')}}" name="userpassword" class="form-control text-dark" placeholder="Password">
            </div>

            <button class="btn mt-2" hx-target="#interaction" hx-post="{{url_for('validation.validate_submit')}}">Create Account</button>

        </form>

    </div>
</div> 

templates/profile_details.html
<div class="container-fluid">
    <div id="interaction" hx-swap="outerHTML" class="container-fluid border border-2 border-black rounded-2 py-3 w-50">

        <div class="fs-1 mb-3">Profile Details</div>

        <div>Your Email</div>
        <div>{{useremail}}</div>


    </div>
</div>

templates/signup.html
<div class="container-fluid mb-3">
    <div id="interaction" hx-swap="outerHTML" class="container-fluid border border-2 border-black rounded-2 py-3 w-50 mb-3">

        <form class="form">

            <div class="fs-1 mb-3">Account Info</div>

            <div class="mb-3" hx-target="this" hx-swap="outerHTML">
                <input type="email" hx-post="{{url_for('validation.validate_email')}}" name="useremail" class="form-control" placeholder="Email">
            </div>
            <div class="mb-3" hx-target="this" hx-swap="outerHTML">
                <input type="password" hx-post="{{url_for('validation.validate_password')}}" name="userpassword" class="form-control text-dark" placeholder="Password">
            </div>

            <div class="fs-1 mb-3">Profile Details</div>
            
            <div class="mb-3" hx-target="this" hx-swap="outerHTML">
                <input type="text" hx-post="{{url_for('validation.validate_username')}}" name="username" class="form-control" placeholder="Username">
            </div>
            <div class="mb-3" hx-target="this" hx-swap="outerHTML">
                <input type="text" hx-post="{{url_for('validation.validate_quote')}}" name="userquote" class="form-control" placeholder="Your Quote">
            </div>

            <button class="btn mt-2" hx-target="#interaction" hx-post="{{url_for('validation.validate_submit')}}">Create Account</button>

        </form>

    </div>
</div>